"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.removeEmployeeController = void 0;
var EmployeesRepository_1 = require("../../repositories/EmployeesRepository");
var RemoveEmployeeController_1 = require("./RemoveEmployeeController");
var RemoveEmployeeUseCase_1 = require("./RemoveEmployeeUseCase");
var employeesRepository = EmployeesRepository_1.EmployeesRepository.getInstance();
var removeEmployeeUseCase = new RemoveEmployeeUseCase_1.RemoveEmployeeUseCase(employeesRepository);
var removeEmployeeController = new RemoveEmployeeController_1.RemoveEmployeeController(removeEmployeeUseCase);
exports.removeEmployeeController = removeEmployeeController;
